version: '3'

services:
  app:
    image: python:3-alpine3.15
    working_dir: /app
    volumes:
      - .:/app
      - pv_contacts:/data
    ports:
      - "3003:3003"
    command: sh -c "pip install -r requirements.txt && python ./app.py"
    
volumes:
  pv_contacts:
